# Usa l'immagine ufficiale di MongoDB
FROM mongo

# Copia lo script di inizializzazione nella cartella /docker-entrypoint-initdb.d/
# COPY init-user.js /docker-entrypoint-initdb.d/

# Abilita l'autenticazione
# CMD ["mongod", "--auth"]