version: '3'
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    container_name: mongodb_users
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      # - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
    env_file: .env
    command: mongod 
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: redis
    command: --port 6380
    ports: 
      - "6380:6380"
    volumes:
      - type: volume
        source: redis-data
        target: /data

    # prima creare un user così tipo poi mandare giù il db e decommentare: db.createUser({user: "admin",pwd: "admin_password",roles: [{ role: "userAdminAnyDatabase", db: "admin" }]})
    # command: --auth 

volumes:
  mongodb_data:
  redis-data: {}
