#!/bin/bash

# Funzione per ottenere il percorso assoluto dello script
get_script_dir() {
  SOURCE="${BASH_SOURCE[0]}"
  while [ -h "$SOURCE" ]; do
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  done
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  echo "$DIR"
}



# Ottieni il percorso del progetto
project_dir=$(get_script_dir)

# Funzione per aprire un nuovo terminale e eseguire il comando in background
open_terminal() {
    osascript -e "tell application \"Terminal\" to do script \"cd $project_dir; $1\""
}





echo "Avvio MongoDB"
open_terminal "cd Auth-Server; docker compose up"

echo "Avvio il server di autenticazione"
open_terminal "cd Auth-Server; cd static/login;npm start"
open_terminal "cd Auth-Server; pipenv run flask --debug run --port 8080"
echo "Avvio il resource server"
open_terminal "cd Auth-Server; cd static/app;npm start"
open_terminal "cd Resource-Server;pipenv run flask --debug run --port 5001"
echo "Avvio l'OTP server"
open_terminal "cd Auth-Server; cd static/otp;npm start"
open_terminal "cd OTP-Server; cd static/otp;npm start; pipenv run flask --debug run"
echo "Tutti i server avviati"