#!/bin/bash
# Funzione per terminare entrambi i processi
terminate_processes() {
    echo "Terminating processes..."
    kill $flask_pid
    echo "Process" $flask_pid "terminated"
}

# Registra la funzione per essere eseguita quando lo script viene interrotto

trap terminate_processes EXIT

cd Resource-Server/


# Avvia flask run in background
pipenv run flask --debug run --port 5001 &

# Salva l'ID del processo flask
flask_pid=$! 

# Cambia directory al login
cd app 

# Avvia npm start in background
npm start &&



# Attendi che entrambi i processi terminino
wait
