#!/bin/bash



cd Auth-Server/


# Avvia flask run in background
pipenv run flask --debug run --port 8080 &

# Salva l'ID del processo flask
flask_pid=$! 

# Cambia directory al login
cd login 

# Avvia npm start in background
npm start &

# Salva l'ID del processo npm
npm_pid=$!

# Funzione per terminare entrambi i processi
terminate_processes() {
    echo "Terminating processes..."
    kill $npm_pid
    echo "Process" $npm_pid "terminated"
    kill $flask_pid
    echo "Process" $flask_pid "terminated"
}

# Registra la funzione per essere eseguita quando lo script viene interrotto
trap terminate_processes EXIT

# Attendi che entrambi i processi terminino
wait
