version: '3'
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongodb_users
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
